# Generated by Django 3.1.4 on 2021-01-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210122_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstore',
            options={},
        ),
    ]
